name: Build and Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      working-directory: ./Frontend
      run: npm install

    - name: Build frontend
      working-directory: ./Frontend
      run: npm run build
      
    - name: Install backend dependencies
      working-directory: ./Backend
      run: npm install
      
    - name: Deploy frontend to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.celestialcrafters.co.ke
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Frontend/build/
        server-dir: /home/celest1/public_html/celestialcraftersweb/

    - name: Deploy backend to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.celestialcrafters.co.ke
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Backend/
        server-dir: /home/celesti1/nodejs/
